// <auto-generated />
using System;
using Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(PuttEmUpDbContext))]
    partial class PuttEmUpDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Match", b =>
                {
                    b.Property<long>("MatchID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("MatchID"));

                    b.Property<bool>("Cancelled")
                        .HasColumnType("bit");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("MatchID");

                    b.ToTable("Matches");

                    b.HasData(
                        new
                        {
                            MatchID = 1L,
                            Cancelled = false,
                            StartDate = new DateTime(2012, 3, 3, 13, 20, 20, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            MatchID = 2L,
                            Cancelled = false,
                            StartDate = new DateTime(2022, 7, 2, 12, 22, 33, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            MatchID = 3L,
                            Cancelled = false,
                            StartDate = new DateTime(2023, 7, 2, 12, 22, 33, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            MatchID = 4L,
                            Cancelled = false,
                            StartDate = new DateTime(2023, 3, 2, 12, 22, 33, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            MatchID = 5L,
                            Cancelled = false,
                            StartDate = new DateTime(2024, 12, 11, 12, 22, 33, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("Domain.MatchPerformance", b =>
                {
                    b.Property<long>("PlayerID")
                        .HasColumnType("bigint");

                    b.Property<long>("MatchID")
                        .HasColumnType("bigint");

                    b.Property<int>("FinalScore")
                        .HasColumnType("int");

                    b.Property<int>("MMRDelta")
                        .HasColumnType("int");

                    b.Property<bool>("WonMatch")
                        .HasColumnType("bit");

                    b.HasKey("PlayerID", "MatchID");

                    b.HasIndex("MatchID");

                    b.ToTable("MatchPerformances");

                    b.HasData(
                        new
                        {
                            PlayerID = 3L,
                            MatchID = 1L,
                            FinalScore = 0,
                            MMRDelta = -100,
                            WonMatch = false
                        },
                        new
                        {
                            PlayerID = 2L,
                            MatchID = 1L,
                            FinalScore = 3,
                            MMRDelta = 100,
                            WonMatch = true
                        },
                        new
                        {
                            PlayerID = 3L,
                            MatchID = 2L,
                            FinalScore = 0,
                            MMRDelta = -100,
                            WonMatch = false
                        },
                        new
                        {
                            PlayerID = 1L,
                            MatchID = 2L,
                            FinalScore = 3,
                            MMRDelta = 100,
                            WonMatch = true
                        },
                        new
                        {
                            PlayerID = 1L,
                            MatchID = 3L,
                            FinalScore = 3,
                            MMRDelta = 100,
                            WonMatch = true
                        },
                        new
                        {
                            PlayerID = 2L,
                            MatchID = 3L,
                            FinalScore = 0,
                            MMRDelta = -100,
                            WonMatch = false
                        },
                        new
                        {
                            PlayerID = 1L,
                            MatchID = 4L,
                            FinalScore = 0,
                            MMRDelta = -100,
                            WonMatch = false
                        },
                        new
                        {
                            PlayerID = 2L,
                            MatchID = 4L,
                            FinalScore = 3,
                            MMRDelta = 100,
                            WonMatch = true
                        },
                        new
                        {
                            PlayerID = 2L,
                            MatchID = 5L,
                            FinalScore = 3,
                            MMRDelta = 100,
                            WonMatch = true
                        },
                        new
                        {
                            PlayerID = 3L,
                            MatchID = 5L,
                            FinalScore = 0,
                            MMRDelta = -100,
                            WonMatch = false
                        });
                });

            modelBuilder.Entity("Domain.Message", b =>
                {
                    b.Property<long>("FromPlayerID")
                        .HasColumnType("bigint");

                    b.Property<long>("ToPlayerID")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("SentTimestamp")
                        .HasColumnType("datetime2");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Reported")
                        .HasColumnType("bit");

                    b.HasKey("FromPlayerID", "ToPlayerID", "SentTimestamp");

                    b.HasIndex("ToPlayerID");

                    b.ToTable("Messages");

                    b.HasData(
                        new
                        {
                            FromPlayerID = 1L,
                            ToPlayerID = 2L,
                            SentTimestamp = new DateTime(2012, 3, 3, 1, 33, 12, 0, DateTimeKind.Unspecified),
                            Content = "ez",
                            Reported = false
                        },
                        new
                        {
                            FromPlayerID = 2L,
                            ToPlayerID = 1L,
                            SentTimestamp = new DateTime(2012, 3, 3, 1, 34, 22, 0, DateTimeKind.Unspecified),
                            Content = ":(",
                            Reported = false
                        },
                        new
                        {
                            FromPlayerID = 1L,
                            ToPlayerID = 3L,
                            SentTimestamp = new DateTime(2022, 3, 3, 1, 33, 12, 0, DateTimeKind.Unspecified),
                            Content = "it's been 10 years, lets play?",
                            Reported = false
                        },
                        new
                        {
                            FromPlayerID = 2L,
                            ToPlayerID = 1L,
                            SentTimestamp = new DateTime(2022, 3, 3, 1, 34, 22, 0, DateTimeKind.Unspecified),
                            Content = "How do I block you??",
                            Reported = false
                        },
                        new
                        {
                            FromPlayerID = 2L,
                            ToPlayerID = 3L,
                            SentTimestamp = new DateTime(2022, 3, 3, 1, 33, 13, 0, DateTimeKind.Unspecified),
                            Content = "hi",
                            Reported = false
                        },
                        new
                        {
                            FromPlayerID = 1L,
                            ToPlayerID = 2L,
                            SentTimestamp = new DateTime(2022, 3, 3, 1, 34, 23, 0, DateTimeKind.Unspecified),
                            Content = "hello",
                            Reported = false
                        });
                });

            modelBuilder.Entity("Domain.Player", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<bool>("AccountDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("AvatarFilePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            AccessFailedCount = 0,
                            AccountDeleted = false,
                            AvatarFilePath = "",
                            ConcurrencyStamp = "83d7c5aa-a2c1-4eb1-8eff-8179fec89dfe",
                            Description = "My Description.",
                            DisplayName = "Aleksandar",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedUserName = "ADMIN",
                            PasswordHash = "AQAAAAIAAYagAAAAEC45QUvRYQCQR1Cd/ZnmLRpYcXeQc3OaA+WV/tGvooLPVXpZs+HfHvzuN/FqmNN8Og==",
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "admin"
                        },
                        new
                        {
                            Id = 2L,
                            AccessFailedCount = 0,
                            AccountDeleted = false,
                            AvatarFilePath = "magnus",
                            ConcurrencyStamp = "40dc99b7-9662-4897-8b40-fe0ea062b2df",
                            Description = "I am very good at this game.",
                            DisplayName = "Magnus",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedUserName = "MAGNUS",
                            PasswordHash = "AQAAAAIAAYagAAAAEE0P/32ODt1bNSYlCGLizw+92utxCPfxn1g0wezUmLbyKfWqWZBYDCqqUSp6hAXHKA==",
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "magnus"
                        },
                        new
                        {
                            Id = 3L,
                            AccessFailedCount = 0,
                            AccountDeleted = false,
                            AvatarFilePath = "",
                            ConcurrencyStamp = "07fd0835-853a-4cc4-bbaf-b9aa6b971668",
                            Description = "I am very bad at this game.",
                            DisplayName = "Bob",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedUserName = "BOB",
                            PasswordHash = "AQAAAAIAAYagAAAAEPBNCbm3wPX/Xa2X+i7WDIeahykRQHJEsVEuNaa3VKvMuLzjXDPTcJ6zKcSZbCMxKw==",
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "bob"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<long>", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Name = "user",
                            NormalizedName = "USER"
                        },
                        new
                        {
                            Id = 2L,
                            Name = "admin",
                            NormalizedName = "ADMIN"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<long>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("RoleId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<long>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<long>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<long>", b =>
                {
                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<long>("RoleId")
                        .HasColumnType("bigint");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = 1L,
                            RoleId = 2L
                        },
                        new
                        {
                            UserId = 2L,
                            RoleId = 1L
                        },
                        new
                        {
                            UserId = 3L,
                            RoleId = 1L
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<long>", b =>
                {
                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Domain.MatchPerformance", b =>
                {
                    b.HasOne("Domain.Match", null)
                        .WithMany()
                        .HasForeignKey("MatchID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Player", null)
                        .WithMany()
                        .HasForeignKey("PlayerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Message", b =>
                {
                    b.HasOne("Domain.Player", null)
                        .WithMany()
                        .HasForeignKey("FromPlayerID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Player", null)
                        .WithMany()
                        .HasForeignKey("ToPlayerID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<long>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<long>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<long>", b =>
                {
                    b.HasOne("Domain.Player", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<long>", b =>
                {
                    b.HasOne("Domain.Player", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<long>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<long>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Player", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<long>", b =>
                {
                    b.HasOne("Domain.Player", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
