// <auto-generated />
using System;
using Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(PuttEmUpDbContext))]
    partial class PuttEmUpDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Match", b =>
                {
                    b.Property<long>("MatchID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("MatchID"));

                    b.Property<bool>("Cancelled")
                        .HasColumnType("bit");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("MatchID");

                    b.ToTable("Matches");

                    b.HasData(
                        new
                        {
                            MatchID = 1L,
                            Cancelled = false,
                            StartDate = new DateTime(2012, 3, 3, 13, 20, 20, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            MatchID = 2L,
                            Cancelled = false,
                            StartDate = new DateTime(2022, 7, 2, 12, 22, 33, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            MatchID = 3L,
                            Cancelled = false,
                            StartDate = new DateTime(2023, 7, 2, 12, 22, 33, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            MatchID = 4L,
                            Cancelled = false,
                            StartDate = new DateTime(2023, 3, 2, 12, 22, 33, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            MatchID = 5L,
                            Cancelled = false,
                            StartDate = new DateTime(2024, 12, 11, 12, 22, 33, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("Domain.MatchPerformance", b =>
                {
                    b.Property<long>("PlayerID")
                        .HasColumnType("bigint");

                    b.Property<long>("MatchID")
                        .HasColumnType("bigint");

                    b.Property<int>("FinalScore")
                        .HasColumnType("int");

                    b.Property<int>("MMRDelta")
                        .HasColumnType("int");

                    b.Property<bool>("WonMatch")
                        .HasColumnType("bit");

                    b.HasKey("PlayerID", "MatchID");

                    b.HasIndex("MatchID");

                    b.ToTable("MatchPerformances");

                    b.HasData(
                        new
                        {
                            PlayerID = 3L,
                            MatchID = 1L,
                            FinalScore = 0,
                            MMRDelta = -100,
                            WonMatch = false
                        },
                        new
                        {
                            PlayerID = 2L,
                            MatchID = 1L,
                            FinalScore = 3,
                            MMRDelta = 100,
                            WonMatch = true
                        },
                        new
                        {
                            PlayerID = 3L,
                            MatchID = 2L,
                            FinalScore = 0,
                            MMRDelta = -100,
                            WonMatch = false
                        },
                        new
                        {
                            PlayerID = 1L,
                            MatchID = 2L,
                            FinalScore = 3,
                            MMRDelta = 100,
                            WonMatch = true
                        },
                        new
                        {
                            PlayerID = 1L,
                            MatchID = 3L,
                            FinalScore = 3,
                            MMRDelta = 100,
                            WonMatch = true
                        },
                        new
                        {
                            PlayerID = 2L,
                            MatchID = 3L,
                            FinalScore = 0,
                            MMRDelta = -100,
                            WonMatch = false
                        },
                        new
                        {
                            PlayerID = 1L,
                            MatchID = 4L,
                            FinalScore = 0,
                            MMRDelta = -100,
                            WonMatch = false
                        },
                        new
                        {
                            PlayerID = 2L,
                            MatchID = 4L,
                            FinalScore = 3,
                            MMRDelta = 100,
                            WonMatch = true
                        },
                        new
                        {
                            PlayerID = 2L,
                            MatchID = 5L,
                            FinalScore = 3,
                            MMRDelta = 100,
                            WonMatch = true
                        },
                        new
                        {
                            PlayerID = 3L,
                            MatchID = 5L,
                            FinalScore = 0,
                            MMRDelta = -100,
                            WonMatch = false
                        });
                });

            modelBuilder.Entity("Domain.Message", b =>
                {
                    b.Property<long>("FromPlayerID")
                        .HasColumnType("bigint");

                    b.Property<long>("ToPlayerID")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("SentTimestamp")
                        .HasColumnType("datetime2");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Reported")
                        .HasColumnType("bit");

                    b.HasKey("FromPlayerID", "ToPlayerID", "SentTimestamp");

                    b.HasIndex("ToPlayerID");

                    b.ToTable("Messages");

                    b.HasData(
                        new
                        {
                            FromPlayerID = 1L,
                            ToPlayerID = 2L,
                            SentTimestamp = new DateTime(2012, 3, 3, 1, 33, 12, 0, DateTimeKind.Unspecified),
                            Content = "ez",
                            Reported = false
                        },
                        new
                        {
                            FromPlayerID = 2L,
                            ToPlayerID = 1L,
                            SentTimestamp = new DateTime(2012, 3, 3, 1, 34, 22, 0, DateTimeKind.Unspecified),
                            Content = ":(",
                            Reported = false
                        },
                        new
                        {
                            FromPlayerID = 1L,
                            ToPlayerID = 3L,
                            SentTimestamp = new DateTime(2022, 3, 3, 1, 33, 12, 0, DateTimeKind.Unspecified),
                            Content = "it's been 10 years, lets play?",
                            Reported = false
                        },
                        new
                        {
                            FromPlayerID = 2L,
                            ToPlayerID = 1L,
                            SentTimestamp = new DateTime(2022, 3, 3, 1, 34, 22, 0, DateTimeKind.Unspecified),
                            Content = "How do I block you??",
                            Reported = false
                        },
                        new
                        {
                            FromPlayerID = 2L,
                            ToPlayerID = 3L,
                            SentTimestamp = new DateTime(2022, 3, 3, 1, 33, 13, 0, DateTimeKind.Unspecified),
                            Content = "hi",
                            Reported = false
                        },
                        new
                        {
                            FromPlayerID = 1L,
                            ToPlayerID = 2L,
                            SentTimestamp = new DateTime(2022, 3, 3, 1, 34, 23, 0, DateTimeKind.Unspecified),
                            Content = "hello",
                            Reported = false
                        });
                });

            modelBuilder.Entity("Domain.Player", b =>
                {
                    b.Property<long>("PlayerID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("PlayerID"));

                    b.Property<bool>("AccountDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("AvatarFilePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MatchmakingRanking")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("int")
                        .HasComputedColumnSql("dbo.GetMMR([PlayerID])");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("PlayerID");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Players");

                    b.HasData(
                        new
                        {
                            PlayerID = 1L,
                            AccountDeleted = false,
                            AvatarFilePath = "",
                            Description = "My Description.",
                            DisplayName = "Aleksandar",
                            MatchmakingRanking = 0,
                            Password = "admin!",
                            Username = "ila"
                        },
                        new
                        {
                            PlayerID = 2L,
                            AccountDeleted = false,
                            AvatarFilePath = "magnus",
                            Description = "I am very good at this game.",
                            DisplayName = "Magnus",
                            MatchmakingRanking = 300,
                            Password = "123456",
                            Username = "magnus"
                        },
                        new
                        {
                            PlayerID = 3L,
                            AccountDeleted = false,
                            AvatarFilePath = "",
                            Description = "I am very bad at this game.",
                            DisplayName = "Bob",
                            MatchmakingRanking = -300,
                            Password = "123abc",
                            Username = "bob"
                        });
                });

            modelBuilder.Entity("Domain.MatchPerformance", b =>
                {
                    b.HasOne("Domain.Match", null)
                        .WithMany()
                        .HasForeignKey("MatchID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Player", null)
                        .WithMany()
                        .HasForeignKey("PlayerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Message", b =>
                {
                    b.HasOne("Domain.Player", null)
                        .WithMany()
                        .HasForeignKey("FromPlayerID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Player", null)
                        .WithMany()
                        .HasForeignKey("ToPlayerID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
